"""sync

Revision ID: 4af47700244a
Revises: a7b8c9d0e1f2
Create Date: 2026-05-12 23:33:24.199615

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4af47700244a"
down_revision: Union[str, Sequence[str], None] = "a7b8c9d0e1f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inquiry_laporan_id"), table_name="inquiry")
    op.drop_index(op.f("ix_inquiry_sender_user_id"), table_name="inquiry")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_inquiry_sender_user_id"), "inquiry", ["sender_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_inquiry_laporan_id"), "inquiry", ["laporan_id"], unique=False
    )
    # ### end Alembic commands ###
