"""create laporan table

Revision ID: 4c261470d6c7
Revises: f6a7b8c9d0e1
Create Date: 2026-04-29 23:25:38.480661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4c261470d6c7"
down_revision: Union[str, Sequence[str], None] = "f6a7b8c9d0e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "laporan",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type", sa.Enum("hilang", "temuan", name="laporantype"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "claim pending",
                "resolved",
                "closed",
                "self-resolved",
                name="laporanstatus",
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("photo", sa.String(), nullable=False),
        sa.Column("lost_at_location_id", sa.UUID(), nullable=True),
        sa.Column("lost_at_date", sa.Date(), nullable=True),
        sa.Column("found_at_location_id", sa.UUID(), nullable=True),
        sa.Column("found_at_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type != 'hilang' OR found_at_location_id IS NULL) AND (type != 'hilang' OR found_at_date IS NULL) AND (type != 'temuan' OR lost_at_location_id IS NULL) AND (type != 'temuan' OR lost_at_date IS NULL)",
            name="ck_laporan_type_location",
        ),
        sa.ForeignKeyConstraint(
            ["found_at_location_id"], ["lokasi.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lost_at_location_id"], ["lokasi.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_users_lokasi_id"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_lokasi_id"), "users", ["lokasi_id"], unique=False)
    op.drop_table("laporan")
    # ### end Alembic commands ###
